### ISSUE TITLE
PDF file corrupted for 27/28th February 2021.

### ISSUE THREAD

**Issue by Shivam60** [skbly7/sbi-tt-rates-historical#2]
PDF file is corrupted for 27th feb 2021
28th Feb 2021 and 1 march 2021

**Comment by skbly7** [comment]
It is just a dump script in an attempt to provide as much information possible. (with no sanitisation checks)
The server's IP has been blocked multiple time, due to which PDF downloaded during that time are corrupted.

Unfortunately due to which, nothing can be done.
